export const PUSH_INCREMENT = 'PUSH_INCREMENT';
export type PUSH_INCREMENT = typeof PUSH_INCREMENT;

export const PUSH_DECREMENT = 'PUSH_DECREMENT';
export type PUSH_DECREMENT = typeof PUSH_DECREMENT;

export const SET_VALUE_TO_EDITOR = 'SET_VALUE_TO_EDITOR';
export type SET_VALUE_TO_EDITOR = typeof SET_VALUE_TO_EDITOR;

export const SET_VALUE_TO_TABLE = 'SET_VALUE_TO_TABLE';
export type SET_VALUE_TO_TABLE = typeof SET_VALUE_TO_TABLE;

export const CHANGE_VALUE_IN_EDITOR = 'CHANGE_VALUE_IN_EDITOR';
export type CHANGE_VALUE_IN_EDITOR = typeof CHANGE_VALUE_IN_EDITOR;

export const SUBMIT_VALUE_FROM_EDITOR = 'SUBMIT_VALUE_FROM_EDITOR';
export type SUBMIT_VALUE_FROM_EDITOR = typeof SUBMIT_VALUE_FROM_EDITOR;
