export const PUSH_INCREMENT = 'PUSH_INCREMENT';
export type PUSH_INCREMENT = typeof PUSH_INCREMENT;

export const PUSH_DECREMENT = 'PUSH_DECREMENT';
export type PUSH_DECREMENT = typeof PUSH_DECREMENT;

export const SET_VALUE_TO_EDITOR = 'SET_VALUE_TO_EDITOR';
export type SET_VALUE_TO_EDITOR = typeof SET_VALUE_TO_EDITOR;

export const SET_VALUE_TO_TABLE = 'SET_VALUE_TO_TABLE';
export type SET_VALUE_TO_TABLE = typeof SET_VALUE_TO_TABLE;

export const CHANGE_VALUE_IN_EDITOR = 'CHANGE_VALUE_IN_EDITOR';
export type CHANGE_VALUE_IN_EDITOR = typeof CHANGE_VALUE_IN_EDITOR;

export const SUBMIT_VALUE_FROM_EDITOR = 'SUBMIT_VALUE_FROM_EDITOR';
export type SUBMIT_VALUE_FROM_EDITOR = typeof SUBMIT_VALUE_FROM_EDITOR;

export const FETCH_MEMBERS = 'FETCH_MEMBERS';
export type FETCH_MEMBERS = typeof FETCH_MEMBERS;

export const STATUS_REQUEST = 'STATUS_REQUEST';
export type STATUS_REQUEST = typeof STATUS_REQUEST;

export const STATUS_ERROR = 'STATUS_ERROR';
export type STATUS_ERROR = typeof STATUS_ERROR;

export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export type STATUS_SUCCESS = typeof STATUS_SUCCESS;

// export const FETCH_MEMBERS_REQUEST = 'FETCH_MEMBERS_REQUEST';
// export type FETCH_MEMBERS_REQUEST = typeof FETCH_MEMBERS_REQUEST;
// export const FETCH_MEMBERS_FAILURE = 'FETCH_MEMBERS_FAILURE';
// export type FETCH_MEMBERS_FAILURE = typeof FETCH_MEMBERS_FAILURE;
// export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';
// export type FETCH_MEMBERS_SUCCESS = typeof FETCH_MEMBERS_SUCCESS;

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export type LOGIN_REQUEST = typeof LOGIN_REQUEST;

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export type LOGIN_SUCCESS = typeof LOGIN_SUCCESS;

export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export type LOGIN_FAILURE = typeof LOGIN_FAILURE;

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export type LOGOUT_REQUEST = typeof LOGOUT_REQUEST;

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export type LOGOUT_SUCCESS = typeof LOGOUT_SUCCESS;

export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export type LOGOUT_FAILURE = typeof LOGOUT_FAILURE;
